version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - ./static:/app/static
      - static_data:/app/staticfiles 
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/data/up1
      - ./static:/app/static
    depends_on:
      - django
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:  
  static_data : 
    driver: local
  static_volume:
    driver: local
